name: fab_circular_menu
description: A Flutter package to create a nice circular menu using a Floating Action Button.
homepage: https://github.com/marianocordoba/fab-circular-menu
version: 0.1.4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
